# Generated by Django 4.2.11 on 2025-09-26 17:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigIntegerField(help_text='Strava Athlete ID', primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('profile_medium', models.CharField(blank=True, max_length=200, null=True)),
                ('profile', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('access_token', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(max_length=255)),
                ('expires_at', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigIntegerField(help_text='Strava Activity ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('distance', models.FloatField(help_text='Distance in meters')),
                ('moving_time', models.IntegerField(help_text='Moving time in seconds')),
                ('elapsed_time', models.IntegerField(help_text='Elapsed time in seconds')),
                ('total_elevation_gain', models.FloatField(help_text='Elevation gain in meters')),
                ('type', models.CharField(help_text='e.g., Run, Ride, Swim', max_length=50)),
                ('sport_type', models.CharField(help_text='e.g., Running, Cycling, Swimming', max_length=50)),
                ('average_speed', models.FloatField(help_text='Average speed in m/s')),
                ('max_speed', models.FloatField(help_text='Max speed in m/s')),
                ('has_heartrate', models.BooleanField(default=False)),
                ('average_heartrate', models.FloatField(blank=True, null=True)),
                ('max_heartrate', models.FloatField(blank=True, null=True)),
                ('start_date', models.DateTimeField(help_text='Start date in UTC')),
                ('start_date_local', models.DateTimeField(help_text='Start date in local time zone')),
                ('timezone', models.CharField(max_length=100)),
                ('calculated_day', models.DateField(db_index=True, help_text='Date part of start_date_local for daily grouping')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='dashboard.athlete')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-start_date_local'],
            },
        ),
    ]
