# Generated by Django 4.2.11 on 2026-01-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='end_latlng',
            field=models.CharField(blank=True, help_text='Ending coordinates [lat, lng]', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='start_latlng',
            field=models.CharField(blank=True, help_text='Starting coordinates [lat, lng]', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='summary_polyline',
            field=models.TextField(blank=True, help_text='Encoded polyline for the activity map', null=True),
        ),
    ]
